openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/add-to-cart:
    post:
      operationId: CartController_addToCart
      summary: Add a product to cart
      parameters:
        - schema:
            type: string
          in: query
          name: terminal
          description: Terminal code (from Seller Center)
          required: true
        - schema:
            type: string
          in: query
          name: channel
          description: Channel code (from Seller Center)
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/AddToCartDto'
      responses:
        '200':
          description: Added order line
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/OrderLineItem'
              examples: {}
        '400':
          description: AddToCart Error Response
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/ErrorV1'
              examples:
                Sản phẩm không tồn tại hoặc đã ngưng bán:
                  value:
                    statusCode: 400
                    message: Sản phẩm không tồn tại hoặc đã ngưng bán
                Khuyến mại lựa chọn không hợp lệ:
                  value:
                    statusCode: 400
                    message: Khuyến mại lựa chọn không hợp lệ
                Sản phẩm không đủ tồn kho:
                  value:
                    statusCode: 400
                    message: Sản phẩm không đủ tồn kho
      tags:
        - Cart management
