openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/add-to-cart:
    post:
      operationId: CartController_addToCart
      summary: Add a product to cart
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/AddToCartDto'
      responses:
        '200':
          description: Added order line
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/OrderLineItem'
              examples: {}
        '412':
          description: AddToCart Error Response
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/Error'
              examples:
                Sản phẩm không tồn tại hoặc đã ngưng bán:
                  value:
                    code: 412
                    message: Sản phẩm không tồn tại hoặc đã ngưng bán
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.ProductNotAvailable
                        message: Sản phẩm không tồn tại hoặc đã ngưng bán
                Khuyến mại lựa chọn không hợp lệ:
                  value:
                    code: 412
                    message: Khuyến mại lựa chọn không hợp lệ
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.PromotionInvalid
                        message: Khuyến mại lựa chọn không hợp lệ
                Sản phẩm không đủ tồn kho:
                  value:
                    code: 412
                    message: Sản phẩm không đủ tồn kho
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.PromotionInvalid
                        message: Sản phẩm không đủ tồn kho
      tags:
        - Cart management
