
openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/apply-coupon:
    post:
      operationId: CartController_applyCoupon
      summary: Apply coupon
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/CheckCouponDto'
      responses:
        '200':
          description: Apply coupon status
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/Error'
              examples:
                Mã khuyến mại không hợp lệ hoặc không được áp dụng với những sản phẩm trong giỏ:
                  value:
                    code: 406
                    message: Mã khuyến mại không hợp lệ hoặc không được áp dụng với những sản phẩm trong giỏ
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.OrderLineNotFound
                        message: Mã khuyến mại không hợp lệ hoặc không được áp dụng với những sản phẩm trong giỏ
                Mã khuyến mại không được áp dụng cho các nhà bán hàng hiện tại:
                  value:
                    code: 406
                    message: rpc.tekoapis.com/cart.v1.CouponInvalid
                    details:
                      - '@type': string
                        message: Mã khuyến mại không được áp dụng cho các nhà bán hàng hiện tại
      tags:
        - Cart management

