openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/clear-coupon:
    delete:
      operationId: CartController_clearCoupon
      summary: Clear coupon
      parameters: []
      responses:
        '200':
          description: Clear coupon status
      tags:
        - Cart management