openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart:
    delete:
      operationId: CartController_clearCart
      summary: Clear cart
      parameters:
        - name: keep_unselected_items
          required: false
          in: query
          schema:
            type: 'boolean'
      responses:
        '200':
          description: Deleted successfully
      tags:
        - Cart management