openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/identity:
    get:
      operationId: IdentityController_getIdentity
      summary: 'Generate cart idenity, can be used to store device id, browser id...'
      parameters: []
      responses:
        '200':
          description: Cart identity token
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/CartIdentity'
      tags:
        - Identity management