openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart:
    get:
      operationId: CartController_getCart
      summary: Get current user cart data
      parameters: []
      responses:
        '200':
          description: Cart data
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/Cart'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/Error'
              examples:
                Thiếu thông tin Terminal:
                  value:
                    code: 404
                    message: Thiếu thông tin Terminal
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.TerminalNotFound
                        message: Thiếu thông tin Terminal
                Thiếu thông tin Channel:
                  value:
                    code: 404
                    message: Thiếu thông tin Terminal
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.ChannelNotFound
                        message: Thiếu thông tin Channel
      tags:
        - Cart management
