openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/order-coupons:
    get:
      operationId: CartController_getOrderCoupon
      summary: Get order coupons
      parameters: []
      responses:
        '200':
          description: Order coupons data
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/OrderCoupons'
      tags:
        - Cart management