openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/payment-methods:
    get:
      operationId: CartController_getPaymentMethods
      summary: Get available payment methods
      parameters:
        - name: orderCode
          required: false
          in: query
          schema:
            type: string
        - name: authorization
          required: true
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Available payment methods
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/PaymentMethodsResponse'
      tags:
        - Cart management