openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  /api/v1/cart/shipping-fee:
    get:
      operationId: CartController_getShippingFee
      summary: Get Shipping fee
      parameters: []
      responses:
        '200':
          description: Get Shipping fee
      tags:
        - Cart management