openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  '/api/v1/cart/order-lines/{orderLineId}':
    delete:
      operationId: CartController_removeOrderLine
      summary: Remove order line from cart
      parameters:
        - name: orderLineId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Delete order line successfully
        '201':
          description: Created
        '412':
          description: AddToCart Error Response
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/Error'
              examples:
                Sản phẩm không tồn tại hoặc đã ngưng bán:
                  value:
                    code: 412
                    message: Sản phẩm không tồn tại trong giỏ hàng
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.OrderLineNotFound
                        message: Sản phẩm không tồn tại trong giỏ hàng
      tags:
        - Cart management
      description: ''
