openapi: 3.0.0
info:
  title: Cart Service
  description: Cart Service API Description
  version: '1.0'
  contact: {}
tags: []
servers: []
paths:
  '/api/v1/cart/order-lines/{orderLineId}':
    put:
      operationId: CartController_updateOrderLine
      summary: Update order line quantity
      parameters:
        - name: orderLineId
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/UpdateOrderLineDto'
      responses:
        '200':
          description: Updated order line
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/tiendv-teko/shopping-cart-v1/main/reference/schema.v1.yaml#/components/schemas/OrderLineItem'
        '412':
          description: Example response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        '@type':
                          type: string
                        message:
                          type: string
              examples:
                Không đủ số lượng sản phẩm:
                  value:
                    code: 412
                    message: Không đủ số lượng sản phẩm
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.ProductQuantityNotEnough
                        message: Không đủ số lượng sản phẩm
                OrderLine Id không tồn tại:
                  value:
                    code: 404
                    message: OrderLine Id không tồn tại
                    details:
                      - '@type': rpc.tekoapis.com/cart.v1.OrderLineNotFound
                        message: OrderLine Id không tồn tại
      tags:
        - Cart management